### ISSUE TITLE
Update /admin/post/write page

### ISSUE THREAD

**Issue by justinyoo** [GetScissorhands/Scissorhands.NET#28]
As a task of #27, the screen needs the following input fields

* [x] Title
* [x] Slug
* [x] Body
* [x] Author
* [x] Tags

It uses Razor syntax and Tag Helpers.

**Comment by justinyoo** [comment]
@Hazealign Fork the repo and do your own stuff there. Once completed, send a PR to dev and we'll start code review from there. If you have any question, please leave messages either here or Slack.

**Comment by haruair** [comment]
:+1:

**Comment by Hazealign** [comment]
Thanks. I'll start it.

**Comment by justinyoo** [comment]
@Hazealign If you need to update other packages such as [Scissorhands.Core](https://github.com/GetScissorhands/Scissorhands.Core), [Scissorhands.Helpers](https://github.com/GetScissorhands/Scissorhands.Helpers), [Scissorhands.Services](https://github.com/GetScissorhands/Scissorhands.Services) or [Scissorhands.Themes](https://github.com/GetScissorhands/Scissorhands.Themes), please raise another issue and put this issue number on there.

Core has been split out to another repo and all others will be separated from this repo by today or so.

**Comment by justinyoo** [comment]
Done
